[package]
name = "k210-soc"
version = "0.1.0"
authors = ["Yifan Wu <shinbokuow@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
k210-hal = { git = "https://github.com/Gerrnperl/k210-hal" }
k210-pac = { git = "https://github.com/wyfcyx/k210-pac" }
riscv = { git = "https://github.com/rcore-os/riscv", features = ["inline-asm"] }
modular-bitfield = "0.11.2"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
